### ISSUE TITLE
ATLAS isn't able to connect to WebAPI

### ISSUE THREAD

**Issue by keesvanbochove** [thehyve/ohdsi-docker#6]
The instructions should probably mention that the docker containers should restart after creating the ohdsi-docker realm (or at least the ATLAS ones should).

After doing that, hitting the OHDSI ATLAS URL (which initially gave an error), and waiting a few minutes, ATLAS does show, but with an error message:
```
application initialization failed
unable to connect to an instance of the webapi.
please contact your administrator to resolve this issue.
```

I don't know if this helps, probably unrelated:
```
$ sudo docker logs fa2777e0c321 | grep err
2021/06/28 15:20:19 [error] 11#11: *6 open() "/usr/share/nginx/html/atlas/js/config-gis.js" failed (2: No such file or directory), client: 172.30.0.4, server: localhost, request: "GET /atlas/js/config-gis.js HTTP/1.1", host: "riglin", referrer: "https://riglin/atlas/"
```

**Comment by blootsvoets** [comment]
I've addressed the first part in #7. The second part is indeed more of a warning than an error. We're not including any GIS config.

**Comment by keesvanbochove** [comment]
I have pulled in the latest version of the main branch, and restarted all containers by using `sudo docker-compose down` and restarting using `bin/start` (by the way, maybe it's good to also add a stop script?) In any case, the problem still persists, navigating to `<hostname>/atlas` redirects me to `<hostname>/atlas/#/configure` but then shows the error message cited above in red text.

**Comment by blootsvoets** [comment]
I’m not sure if this was the problem, but webapi takes about 2-3 minutes to start up. Before that time, you’ll get the text in red. I’d have to check if you can deploy this on a local host (it’s meant for a server), because the stack uses a letsencrypt SSL certificate, which is only available if the website is resolvable with DNS.

**Comment by keesvanbochove** [comment]
There is a certificate generated, and I can access both the Keycloak and ATLAS GUI's, although I do get a certificate warning from the browser.
When generating the synthea dataset, I also get an error that relates to WebAPI connectivity:
```=== Preparing results schema ===
Initializing concept hierarchy
Querying DDL from http://riglin:8080/WebAPI/ddl/results?dialect=postgresql&schema=cdm_synthea1k_results&vocabSchema=vocab&tempSchema=temp&initConceptHierarchy=true
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to riglin port 8080: Connection refused```
My `BASE_URL` is currently set to `http://riglin:8080`, should this be HTTPS then?

**Comment by keesvanbochove** [comment]
OK, so I realized that I probably should have left `BASE_URL` at `http://localhost:8080` because the Docker container may have a different IP address and I'm not sure if traffic to port 8080 on the Docker host is forwarded to port 8080 on the webapi container.
However, I also noticed something in the WebAPI container log:
```
2021-07-01 20:52:04.920 ERROR main org.ohdsi.webapi.AuthDataSource -  - Failed to initialize connection to DB used for authentication: Failed to initialize pool: Connection to 54.209.111.128:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```
Where is this IP address coming from?

**Comment by keesvanbochove** [comment]
@blootsvoets the issue isn't solved for me, have you been able to reproduce it?
